### PR TITLE
Make React a peer dependency

### PR DESCRIPTION
**Pull request by denkristoffer**
Make React a peer dependency and allow React 16.

### CODE REVIEW

**Comment by alex3165** [comment]
The CI is failing when trying to parse the package.json file, can you try to run `npm i` and see what is the issue? I think `prop-types` need to be a `peerDepencies` too. Thanks for the PR 👍

**Comment by denkristoffer** [comment]
Sorry, my bad! I forgot a comma. I've moved `prop-types` to peer dependencies as well :)

Edit: Should it be added to `devDependencies` as well?

**Comment by alex3165** [comment]
Thanks, yes it should be in `devDependencies` too.

**Comment by denkristoffer** [comment]
Fixed tests and rebased :) I also moved `prop-types` back to `dependencies` as per https://github.com/facebook/prop-types/issues/44#issuecomment-299238787 – it makes more sense, I think. Hope you're okay with that 👍

**Pull request merged**
